import Head from "next/head";
import { Inter } from "next/font/google";
import styled from "@emotion/styled";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className={`${inter.className}`}>
        <Title>Home</Title>
        <Link href="/case_studies"><strong>Read Case Study Posts</strong></Link>
        <br />
        <Link href="/entries"><strong>Read Entry Posts</strong></Link>
      </Main>
    </>
  );
}

const Main = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;
const Title = styled.h1`
  margin-bottom: 20px;
`;
